In [1]:
!pip install google-generativeai

Requirement already satisfied: google-generativeai in /usr/local/lib/python3.12/dist-packages (0.8.5)
Requirement already satisfied: google-ai-generativelanguage==0.6.15 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (0.6.15)
Requirement already satisfied: google-api-core in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.28.0)
Requirement already satisfied: google-api-python-client in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.185.0)
Requirement already satisfied: google-auth>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.38.0)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (5.29.5)
Requirement already satisfied: pydantic in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (2.11.10)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.67.1)
Requirement already satisfied: typing-extensions in /usr/local/lib/python3.12/dist-packages (from google-generativeai) (4.15.0)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-ai-generativelanguage==0.6.15->google-generativeai) (1.26.1)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (1.71.0)
Requirement already satisfied: requests<3.0.0,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-api-core->google-generativeai) (2.32.4)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.15.0->google-generativeai) (4.9.1)
Requirement already satisfied: httplib2<1.0.0,>=0.19.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.31.0)
Requirement already satisfied: google-auth-httplib2<1.0.0,>=0.2.0 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (0.2.0)
Requirement already satisfied: uritemplate<5,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from google-api-python-client->google-generativeai) (4.2.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (2.33.2)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic->google-generativeai) (0.4.2)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.10.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,!=2.8.*,!=2.9.*,<3.0.0dev,>=1.34.1->google-ai-generativelanguage==0.6.15->google-generativeai) (1.71.2)
Requirement already satisfied: pyparsing<4,>=3.0.4 in /usr/local/lib/python3.12/dist-packages (from httplib2<1.0.0,>=0.19.0->google-api-python-client->google-generativeai) (3.2.5)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.15.0->google-generativeai) (0.6.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.18.0->google-api-core->google-generativeai) (2025.10.5)

# Task
Set up a Retrieval Augmented Generation (RAG) backend using data from `gs://labs.roitraining.com/alaska-dept-of-snow` and integrate it with the existing Gemini chatbot to enhance its responses with retrieved context.

## Environment Setup

### Subtask:
Install the necessary Python libraries for interacting with Google Cloud Storage and RAG Engine.

**Reasoning**:
The subtask requires installing specific Python libraries. I will use `pip install` within a code block to install `google-cloud-storage` and `vertexai`.

In [2]:
pip install google-cloud-storage vertexai

Requirement already satisfied: google-cloud-storage in /usr/local/lib/python3.12/dist-packages (2.19.0)
Requirement already satisfied: vertexai in /usr/local/lib/python3.12/dist-packages (1.71.1)
Requirement already satisfied: google-auth<3.0dev,>=2.26.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.38.0)
Requirement already satisfied: google-api-core<3.0.0dev,>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.28.0)
Requirement already satisfied: google-cloud-core<3.0dev,>=2.3.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.4.3)
Requirement already satisfied: google-resumable-media>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.7.2)
Requirement already satisfied: requests<3.0.0dev,>=2.18.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (2.32.4)
Requirement already satisfied: google-crc32c<2.0dev,>=1.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-storage) (1.7.1)
Requirement already satisfied: google-cloud-aiplatform==1.71.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform[all]==1.71.1->vertexai) (1.71.1)
Requirement already satisfied: proto-plus<2.0.0dev,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.26.1)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<6.0.0dev,>=3.20.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (5.29.5)
Requirement already satisfied: packaging>=14.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (25.0)
Requirement already satisfied: google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (3.38.0)
Requirement already satisfied: google-cloud-resource-manager<3.0.0dev,>=1.3.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.15.0)
Requirement already satisfied: shapely<3.0.0dev in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.1.2)
Requirement already satisfied: pydantic<3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.11.10)
Requirement already satisfied: docstring-parser<1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.17.0)
WARNING: google-cloud-aiplatform 1.71.1 does not provide the extra 'all'
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.56.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0dev,>=2.15.0->google-cloud-storage) (1.71.0)
Requirement already satisfied: cachetools<6.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0dev,>=2.26.1->google-cloud-storage) (5.5.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0dev,>=2.26.1->google-cloud-storage) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth<3.0dev,>=2.26.1->google-cloud-storage) (4.9.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0dev,>=2.18.0->google-cloud-storage) (2025.10.5)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.76.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]!=2.0.*,!=2.1.*,!=2.2.*,!=2.3.*,!=2.4.*,!=2.5.*,!=2.6.*,!=2.7.*,<3.0.0dev,>=1.34.1->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.71.2)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.9.0.post0)
Requirement already satisfied: grpc-google-iam-v1<1.0.0,>=0.14.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-resource-manager<3.0.0dev,>=1.3.3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.14.3)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth<3.0dev,>=2.26.1->google-cloud-storage) (0.6.1)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.7.0)
Requirement already satisfied: pydantic-core==2.33.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.33.2)
Requirement already satisfied: typing-extensions>=4.12.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (0.4.2)
Requirement already satisfied: numpy>=1.21 in /usr/local/lib/python3.12/dist-packages (from shapely<3.0.0dev->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (2.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery!=3.20.0,<4.0.0dev,>=1.15.0->google-cloud-aiplatform==1.71.1->google-cloud-aiplatform[all]==1.71.1->vertexai) (1.17.0)

## Authenticate Google Cloud

### Subtask:
Set up Google Cloud authentication to access the GCS bucket.

**Reasoning**:
To authenticate Google Cloud in a Colab environment, I need to import `google.colab.auth` and then call its `authenticate_user()` function.

In [3]:
import google.colab.auth
google.colab.auth.authenticate_user()
print("Google Cloud authentication initiated.")

WARNING: google.colab.auth.authenticate_user() is not supported in Colab Enterprise.
Google Cloud authentication initiated.

In [4]:
import os
from google.cloud import bigquery
from google.cloud import aiplatform

PROJECT_ID = "qwiklabs-gcp-03-42d2ec04c144"
DATASET_ID = "alaska_dept_snow"
APP_LOCATION = "us-central1"
BQ_LOCATION = "US"
TABLE_ID = "alaska_snow_faqs"
EMBED_TABLE_ID = "alaska_snow_embeddings"

os.environ["GOOGLE_CLOUD_PROJECT"] = PROJECT_ID
aiplatform.init(project=PROJECT_ID, location=APP_LOCATION)
bq_client = bigquery.Client(project=PROJECT_ID, location=BQ_LOCATION)

dataset_ref = bigquery.Dataset(f"{PROJECT_ID}.{DATASET_ID}")
dataset_ref.location = BQ_LOCATION

gcs_uri = "gs://labs.roitraining.com/alaska-dept-of-snow/alaska-dept-of-snow-faqs.csv"

table_exists = False
try:
    dataset_ref = bq_client.create_dataset(dataset_ref)  # will fail if exists
    print(f"Created dataset {dataset_ref.full_dataset_id}")
except Exception as e:
    print(f"Dataset may already exist: {e}")
    table_exists = True

if table_exists == False:
   # Define load job: CSV → BigQuery
   table_ref = f"{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}"

   job_config = bigquery.LoadJobConfig(
       source_format=bigquery.SourceFormat.CSV,
       skip_leading_rows=1,
       autodetect=True,
   )

   load_job = bq_client.load_table_from_uri(
       gcs_uri,
       table_ref,
       job_config=job_config,
   )

   print("⏳ Loading CSV into BigQuery...")
   load_job.result()
   print("✅ Load complete")

   table = bq_client.get_table(table_ref)
   print("Loaded rows:", table.num_rows)
   print("Schema:", table.schema)
else:
  print("✅ Table already exists")

Dataset may already exist: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-03-42d2ec04c144/datasets?prettyPrint=false: Already Exists: Dataset qwiklabs-gcp-03-42d2ec04c144:alaska_dept_snow
✅ Table already exists

Create embeddings and store in new table.

In [5]:
from vertexai.language_models import TextEmbeddingModel

embedding_model = TextEmbeddingModel.from_pretrained("text-embedding-004")

schema = [
    bigquery.SchemaField("faq_id", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("question", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("answer", "STRING", mode="REQUIRED"),
    bigquery.SchemaField("combined_text", "STRING", mode="REQUIRED"),
    # Store embedding as an ARRAY<FLOAT64>
    bigquery.SchemaField("embedding", "FLOAT64", mode="REPEATED"),
]

embedding_table_ref = bigquery.Table(
    f"{PROJECT_ID}.{DATASET_ID}.{EMBED_TABLE_ID}",
    schema=schema,
)

embeddings_exist = False
try:
    embedding_table_ref = bq_client.create_table(embedding_table_ref)
    print(f"✅ Created embedding table {embedding_table_ref.full_table_id}")
except Exception as e:
    print(f"Embedding already exist: {e}")
    embeddings_exist = True

#embeddings_exist = False
if embeddings_exist == False:
   query = f"""
   SELECT
     CAST(ROW_NUMBER() OVER() AS STRING) AS faq_id,
     string_field_0 AS question,  -- Map string_field_0 to 'question' alias
     string_field_1 AS answer     -- Map string_field_1 to 'answer' alias
   FROM `{PROJECT_ID}.{DATASET_ID}.{TABLE_ID}`
   """
   faq_rows = list(bq_client.query(query))

   print(f"Generating embeddings for {len(faq_rows)} rows...")

   rows_to_insert = []

   for row in faq_rows:
       faq_id = row["faq_id"]
       question = row["question"]
       answer = row["answer"]
       combined_text = f"Q: {question}\nA: {answer}"

        # 🧠 Call the embeddings model
       embedding_response = embedding_model.get_embeddings([combined_text])
       embedding = embedding_response[0].values

       rows_to_insert.append(
           {
               "faq_id": faq_id,
               "question": question,
               "answer": answer,
               "combined_text": combined_text,
               "embedding": embedding,
           }
       )
   # Insert into BigQuery
   errors = bq_client.insert_rows_json(
       f"{PROJECT_ID}.{DATASET_ID}.{EMBED_TABLE_ID}",
       rows_to_insert,
   )

   if errors:
       print("❌ Errors while inserting embeddings:", errors)
   else:
       print("✅ Successfully stored embeddings in BigQuery")

Embedding already exist: 409 POST https://bigquery.googleapis.com/bigquery/v2/projects/qwiklabs-gcp-03-42d2ec04c144/datasets/alaska_dept_snow/tables?prettyPrint=false: Already Exists: Table qwiklabs-gcp-03-42d2ec04c144:alaska_dept_snow.alaska_snow_embeddings

# Task
Define a Python function that takes a user query, generates an embedding for it using the Vertex AI `TextEmbeddingModel`, and executes a BigQuery SQL query to find the top matching rows from the `alaska_dept_snow.alaska_snow_embeddings` table using cosine distance. Call this function with the query "How do I report an unplowed road?" and display the retrieved question-answer pairs to verify the vector search implementation.

## Define Vector Search Function

### Subtask:
Create a Python function to embed a user query and search the BigQuery embeddings table for the most similar FAQs using cosine distance.

**Reasoning**:
Define the `search_faqs` function to embed a user query and perform a vector search in BigQuery using cosine distance, as requested.

In [6]:
def search_faqs(query_text):
    # Generate embedding for the query
    embedding_response = embedding_model.get_embeddings([query_text])
    query_embedding = embedding_response[0].values

    # Construct the SQL query for vector search
    query = f"""
        SELECT
            question,
            answer,
            ML.DISTANCE(embedding, {query_embedding}, 'COSINE') AS distance
        FROM
            `{PROJECT_ID}.{DATASET_ID}.{EMBED_TABLE_ID}`
        ORDER BY
            distance ASC
        LIMIT 5
    """

    # Execute the query
    query_job = bq_client.query(query)
    return query_job

print("Vector search function 'search_faqs' defined.")

Vector search function 'search_faqs' defined.

**Reasoning**:
The `search_faqs` function is defined. To verify the implementation and satisfy the task requirement, I will call this function with the specified query "How do I report an unplowed road?" and print the retrieved question-answer pairs.

In [7]:
query_text = "How do I report an unplowed road?"
results = search_faqs(query_text)

print(f"Query: {query_text}\n")
print("Top matching FAQs:")
for row in results:
    print(f"Question: {row.question}")
    print(f"Answer: {row.answer}")
    print(f"Cosine Distance: {row.distance}")
    print("-" * 80)

query_text = "How are emergency snow response protocols activated?"
results = search_faqs(query_text)

print(f"\n\n")
print(f"Query: {query_text}\n")
print("Top matching FAQs:")
for row in results:
    print(f"Question: {row.question}")
    print(f"Answer: {row.answer}")
    print(f"Cosine Distance: {row.distance}")
    print("-" * 80)

Query: How do I report an unplowed road?

Top matching FAQs:
Question: Who do I contact to report an unplowed road?
Answer: Contact your local ADS regional office. Each region maintains a hotline for snow-related service requests and emergencies.
Cosine Distance: 0.18932653168271674
--------------------------------------------------------------------------------
Question: Who do I contact to report an unplowed road?
Answer: Contact your local ADS regional office. Each region maintains a hotline for snow-related service requests and emergencies.
Cosine Distance: 0.18932653168271674
--------------------------------------------------------------------------------
Question: Where can I file a complaint about late plowing?
Answer: You can file a complaint through the ADS website or call the district office responsible for your region. Complaints are addressed in order of urgency.
Cosine Distance: 0.28027807774856894
--------------------------------------------------------------------------------
Question: Where can I file a complaint about late plowing?
Answer: You can file a complaint through the ADS website or call the district office responsible for your region. Complaints are addressed in order of urgency.
Cosine Distance: 0.28027807774856894
--------------------------------------------------------------------------------
Question: How can I find out if my street is scheduled to be plowed?
Answer: Check the ADS website’s interactive map or call your regional office. Schedules are updated in real time, especially during heavy snowfall.
Cosine Distance: 0.3190666491432499
--------------------------------------------------------------------------------



Query: How are emergency snow response protocols activated?

Top matching FAQs:
Question: How are emergency snow response protocols activated?
Answer: When a severe storm is forecast, ADS coordinates with the State Emergency Operations Center, mobilizing additional crews and pre-positioning equipment.
Cosine Distance: 0.20539169460559914
--------------------------------------------------------------------------------
Question: How are emergency snow response protocols activated?
Answer: When a severe storm is forecast, ADS coordinates with the State Emergency Operations Center, mobilizing additional crews and pre-positioning equipment.
Cosine Distance: 0.20539169460559947
--------------------------------------------------------------------------------
Question: What should I do if I see a stranded vehicle during a snowstorm?
Answer: Call 911 for emergencies. For non-emergencies, notify ADS or your local police to help coordinate assistance and remove hazards from the road.
Cosine Distance: 0.3858338601653768
--------------------------------------------------------------------------------
Question: What should I do if I see a stranded vehicle during a snowstorm?
Answer: Call 911 for emergencies. For non-emergencies, notify ADS or your local police to help coordinate assistance and remove hazards from the road.
Cosine Distance: 0.385833860165377
--------------------------------------------------------------------------------
Question: How does ADS communicate with other state agencies?
Answer: ADS uses a statewide interagency platform to share weather data, route priorities, and incident reports, ensuring coordinated responses during severe snow events.
Cosine Distance: 0.3886792996549039
--------------------------------------------------------------------------------

In [30]:
import google.generativeai as genai
from google.cloud import modelarmor_v1
from google.cloud.modelarmor_v1.types import FilterMatchState
from google.api_core.client_options import ClientOptions
import logging

# Configure logging
logging.basicConfig(
    filename='chatbot_history.log',
    level=logging.INFO,
    format='%(asctime)s - %(message)s',
    force=True
)

# Replace with your actual API key
API_KEY = "AIzaSyC9ncqGqz1Zt6CE_4iG6afqmkctuTDQ-Zs"
genai.configure(api_key=API_KEY)

# Define your system instructions here
system_instructions = """
You are a helpful and friendly chatbot that answers weather related for the Alaska Snow Department.
At the beginning of the conversation only, you should greet the user nicely and hope they are staying warm.
If context is provided, use that context to answer the question. Otherwise, say you don't know.
"""


model = genai.GenerativeModel(
    'gemini-2.5-flash',
    system_instruction=system_instructions
)

armor_client = modelarmor_v1.ModelArmorClient(
      transport="rest",
      client_options=ClientOptions(
          api_endpoint=f"modelarmor.us-central1.rep.googleapis.com"
      ),
  )

def sanitize_input(user_input):
  user_input_data = modelarmor_v1.DataItem()
  user_input_data.text = user_input
  request = modelarmor_v1.SanitizeUserPromptRequest(
      name=f"projects/qwiklabs-gcp-03-42d2ec04c144/locations/us-central1/templates/request-model-armor",
      user_prompt_data=user_input_data,
  )

  response = armor_client.sanitize_user_prompt(request=request)
  return response.sanitization_result.filter_match_state


def sanitize_response(model_response):
  # Initialize request argument(s)
  model_response_data = modelarmor_v1.DataItem(text=model_response)

  # Prepare request for sanitizing model response.
  request = modelarmor_v1.SanitizeModelResponseRequest(
      name=f"projects/qwiklabs-gcp-03-42d2ec04c144/locations/us-central1/templates/response-model-armor",
      model_response_data=model_response_data,
  )

  # Sanitize the model response.
  response = armor_client.sanitize_model_response(request=request)
  return response.sanitization_result.filter_match_state

def build_context_from_results(results) -> str:
    """Combine relevant FAQs into a context string for Gemini."""
    context_chunks = []
    for r in results:
        context_chunks.append(
            f"Question: {r['question']}\nAnswer: {r['answer']}"
        )
    return "\n\n---\n\n".join(context_chunks)



def get_gemini_response(prompt):
  response = chat.send_message(prompt)
  return response.text

def get_raq_response(prompt):
  rag_results = search_faqs(prompt)

  #print(f"RAG Results: {rag_results}")

  context = ""
  if rag_results:
    context = build_context_from_results(rag_results)

  prompt = f"""
    Context:
    {context}

    User question:
    {prompt}

    Answer:
    """

  #print(f"Gemini Response: " + get_gemini_response(prompt))
  #return get_gemini_response(prompt)

  response = chat.send_message(prompt)
  return response.text

chat = model.start_chat(history=[])

def greet_user():

  # Generate a greeting using Gemini
  initial_prompt = "Greet the user nicely saying you hope they are staying warm and dry, then introduce yourself as the Alaska Snow Department chatbot."
  greeting_response = chat.send_message(initial_prompt)
  print_and_log(f"Chatbot: {greeting_response.text}\n")
  #print(f"GREETING")

def print_and_log(message):
  print(message)
  logging.info(f"Chatbot Response: {message}")

def chatbot():
  greet_user()

  session_active = True
  while session_active:
    user_input = input("You: ")
    logging.info(f"User Input: {user_input}")
    print(f"")

    if user_input.lower() in ["quit", "exit", "bye"]:
      print_and_log("Chatbot: Goodbye!")
      logging.info("User ended conversation.")
      session_active = False
      break
    if sanitize_input(user_input) == FilterMatchState.MATCH_FOUND:
      print_and_log("I'm sorry, could you please ask that again in a nicer another way.")
      logging.info("User input filtered by Model Armor.")
      continue

    #bot_response = get_gemini_response(user_input)
    bot_response = get_raq_response(user_input)

    if sanitize_response(bot_response) == FilterMatchState.MATCH_FOUND:
      print_and_log("I'm sorry, I cannot answer that for safety reasons.")
      logging.info("Bot response filtered by Model Armor.")
      continue

    print_and_log(f"Chatbot: {bot_response}")
    print(f"")

chatbot()

Chatbot: Hello there! I hope you are staying warm and dry. I'm the Alaska Snow Department chatbot, here to help you with your weather-related questions.

You: What should I do if I see a stranded vehicle during a snowstorm?

Chatbot: Call 911 for emergencies. For non-emergencies, notify ADS or your local police to help coordinate assistance and remove hazards from the road.

KeyboardInterrupt: Interrupted by user

You: sds

In [31]:
pip install ipytest

sdsCollecting ipytest
  Downloading ipytest-0.14.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: ipython in /usr/local/lib/python3.12/dist-packages (from ipytest) (7.34.0)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from ipytest) (25.0)
Requirement already satisfied: pytest>=5.4 in /usr/local/lib/python3.12/dist-packages (from ipytest) (8.4.2)
Requirement already satisfied: iniconfig>=1 in /usr/local/lib/python3.12/dist-packages (from pytest>=5.4->ipytest) (2.3.0)
Requirement already satisfied: pluggy<2,>=1.5 in /usr/local/lib/python3.12/dist-packages (from pytest>=5.4->ipytest) (1.6.0)
Requirement already satisfied: pygments>=2.7.2 in /usr/local/lib/python3.12/dist-packages (from pytest>=5.4->ipytest) (2.19.2)
Requirement already satisfied: setuptools>=18.5 in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (75.2.0)
Requirement already satisfied: jedi>=0.16 in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (0.19.2)
Requirement already satisfied: decorator in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (4.4.2)
Requirement already satisfied: pickleshare in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (0.7.5)
Requirement already satisfied: traitlets>=4.2 in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (5.7.1)
Requirement already satisfied: prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (3.0.52)
Requirement already satisfied: backcall in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (0.2.0)
Requirement already satisfied: matplotlib-inline in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (0.2.1)
Requirement already satisfied: pexpect>4.3 in /usr/local/lib/python3.12/dist-packages (from ipython->ipytest) (4.9.0)
Requirement already satisfied: parso<0.9.0,>=0.8.4 in /usr/local/lib/python3.12/dist-packages (from jedi>=0.16->ipython->ipytest) (0.8.5)
Requirement already satisfied: ptyprocess>=0.5 in /usr/local/lib/python3.12/dist-packages (from pexpect>4.3->ipython->ipytest) (0.7.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.12/dist-packages (from prompt-toolkit!=3.0.0,!=3.0.1,<3.1.0,>=2.0.0->ipython->ipytest) (0.2.14)
Downloading ipytest-0.14.2-py3-none-any.whl (18 kB)
Installing collected packages: ipytest
Successfully installed ipytest-0.14.2

In [32]:
import ipytest
import pytest
import pandas as pd
import logging

# Configure ipytest
ipytest.autoconfig()

# Load the FAQs to use as test data
faq_df = pd.read_csv('/content/alaska-dept-of-snow-faqs.csv')

# Display the first few rows to understand the structure
print("Loaded FAQs for testing:")
display(faq_df.head())

Loaded FAQs for testing:

,question,answer
0,When was the Alaska Department of Snow establi...,The Alaska Department of Snow (ADS) was establ...
1,What is the mission of the Alaska Department o...,"Our mission is to ensure safe, efficient trave..."
2,How does ADS coordinate plowing across differe...,ADS works with local municipalities and region...
3,Who do I contact to report an unplowed road?,Contact your local ADS regional office. Each r...
4,Does ADS oversee school closure decisions?,"While ADS provides data on snow conditions, fi..."

In [33]:
%%ipytest -vv

def test_rag_response_not_empty():
    """
    Test that the RAG response function returns a non-empty string
    for a valid question from the FAQ dataset.
    """
    # Pick the first question from the dataset as a test case
    # Assuming the first column is the question. Adjust if column names differ.
    test_question = faq_df.iloc[0, 0]
    expected_answer_snippet = faq_df.iloc[0, 1]

    print(f"\nTesting with Question: {test_question}")

    # Call the RAG function (using the function defined in the notebook)
    # Note: The user referred to 'get_rag_result' but the defined function is 'get_raq_response'
    response = get_raq_response(test_question)

    print(f"Received Response: {response}")

    # Assertions
    assert response is not None
    assert isinstance(response, str)
    assert len(response) > 0
    # Check if the response is not just an error message (basic check)
    assert "safety reasons" not in response.lower()
    assert "nicer another way" not in response.lower()

======================================= test session starts ========================================
platform linux -- Python 3.12.12, pytest-8.4.2, pluggy-1.6.0 -- /usr/bin/python3
cachedir: .pytest_cache
rootdir: /content
plugins: langsmith-0.4.38, typeguard-4.4.4, anyio-4.11.0
collecting ... collected 1 item

t_e9ce1aca192b4c1aa2e68f09f799c5b9.py::test_rag_response_not_empty PASSED                    [100%]

======================================== 1 passed in 3.07s =========================================

## Use Gen AI Evaluation SDK to Evaluate Models

In [ ]:
%pip install -U -q google-cloud-aiplatform[evaluation]
%pip install -U -q datasets

In [ ]:
PROJECT_ID = "qwiklabs-gcp-03-42d2ec04c144"  # @param {type:"string"}
LOCATION = "us-central1"  # @param {type:"string"}
OUTPUT_URI_PREFIX = "gs://genai-evaluation-results"  # @param {type:"string"}

import vertexai

vertexai.init(project=PROJECT_ID, location=LOCATION)

# Only if your bucket doesn't already exist: Uncomment the following code to create your Cloud Storage bucket.
# ! gsutil mb -l {LOCATION} -p {PROJECT_ID} {OUTPUT_URI_PREFIX}

In [ ]:
from vertexai.evaluation import (
    EvalTask,
    MetricPromptTemplateExamples,
    PairwiseMetric,
    PairwiseMetricPromptTemplate,
    PointwiseMetric,
    PointwiseMetricPromptTemplate,
)
from vertexai.generative_models import GenerativeModel
import pandas as pd

### Helper functions

In [ ]:
import random
import string

from IPython.display import HTML, Markdown, display
import plotly.graph_objects as go


def display_explanations(eval_result, metrics=None, n=1):
    """Display the explanations."""
    style = "white-space: pre-wrap; width: 1500px; overflow-x: auto;"
    metrics_table = eval_result.metrics_table
    df = metrics_table.sample(n=n)

    if metrics:
        df = df.filter(
            ["response", "baseline_model_response"]
            + [
                metric
                for metric in df.columns
                if any(selected_metric in metric for selected_metric in metrics)
            ]
        )
    for index, row in df.iterrows():
        for col in df.columns:
            display(HTML(f"<div style='{style}'><h4>{col}:</h4>{row[col]}</div>"))
        display(HTML("<hr>"))


def display_eval_result(eval_result, title=None, metrics=None):
    """Display the evaluation results."""
    summary_metrics, metrics_table = (
        eval_result.summary_metrics,
        eval_result.metrics_table,
    )

    metrics_df = pd.DataFrame.from_dict(summary_metrics, orient="index").T
    if metrics:
        metrics_df = metrics_df.filter(
            [
                metric
                for metric in metrics_df.columns
                if any(selected_metric in metric for selected_metric in metrics)
            ]
        )
        metrics_table = metrics_table.filter(
            [
                metric
                for metric in metrics_table.columns
                if any(selected_metric in metric for selected_metric in metrics)
            ]
        )

    if title:
        # Display the title with Markdown for emphasis
        display(Markdown(f"## {title}"))
    # Display the summary metrics DataFrame
    display(Markdown("### Summary Metrics"))
    display(metrics_df)
    # Display the metrics table DataFrame
    display(Markdown("### Row-based Metrics"))
    display(metrics_table)

### Load an evaluation dataset

Load a subset of the `OpenOrca` dataset using the `huggingface/datasets` library. We will use 10 samples from the first 100 rows of the "train" split of `OpenOrca` dataset to demonstrate evaluating prompts and model responses in this Colab.

#### Dataset Summary

The OpenOrca dataset is a collection of augmented [FLAN Collection data](https://arxiv.org/abs/2301.13688). Currently ~1M GPT-4 completions, and ~3.2M GPT-3.5 completions. It is tabularized in alignment with the distributions presented in the ORCA paper and currently represents a partial completion of the full intended dataset, with ongoing generation to expand its scope. The data is primarily used for training and evaluation in the field of natural language processing.

In [ ]:
from datasets import load_dataset

ds = (
    load_dataset(
        "Open-Orca/OpenOrca",
        data_files="1M-GPT4-Augmented.parquet",
        split="train[:100]",
    )
    .to_pandas()
    .drop(columns=["id"])
    .rename(columns={"response": "reference"})
)

dataset = ds.sample(n=10)

In [ ]:
dataset.head()

### Run evaluation

#### Use model-based pointwise metrics

In [ ]:
# Model to be evaluated
model = GenerativeModel(
    "gemini-2.5-pro",
    generation_config={"temperature": 0.6, "max_output_tokens": 256, "top_k": 1},
)

In [ ]:
supported_example_metric_names = (
    MetricPromptTemplateExamples.list_example_metric_names()
)

for metric in supported_example_metric_names:
    print(metric)

In [ ]:
# Create a pointwise metric
POINTWISE_METRIC = PointwiseMetric(
    metric='coherence',
    metric_prompt_template=MetricPromptTemplateExamples.get_prompt_template(
        'coherence'
    ),
)

In [ ]:
# Define an EvalTask with a pointwise model-based metric
pointwise_eval_task = EvalTask(
    dataset=dataset,
    metrics=[POINTWISE_METRIC],
    output_uri_prefix=OUTPUT_URI_PREFIX,
)

pointwise_result = pointwise_eval_task.evaluate(
    model=model,
    prompt_template="# System_prompt\n{system_prompt} # Question\n{question}",
)

In [ ]:
display_eval_result(pointwise_result)

In [ ]:
display_explanations(pointwise_result, metrics=['coherence'], n=1)

#### Use model-based pairwise metrics

In [ ]:
# Create a pairwise metric
PAIRWISE_METRIC = PairwiseMetric(
    metric='pairwise_coherence',
    metric_prompt_template=MetricPromptTemplateExamples.get_prompt_template(
        'pairwise_coherence'
    ),
    # Define a baseline model for pairwise comparison
    baseline_model=GenerativeModel("gemini-2.5-flash"),
)

In [ ]:
pairwise_eval_task = EvalTask(
    dataset=dataset,
    metrics=[PAIRWISE_METRIC],
    output_uri_prefix=OUTPUT_URI_PREFIX,
)
# Specify a candidate model for pairwise comparison
pairwise_result = pairwise_eval_task.evaluate(
    model=model,
    prompt_template="# System_prompt\n{system_prompt} # Question\n{question}",
)

In [ ]:
display_eval_result(
    pairwise_result,
    title="Gemini 2.5 Flash vs. Gemini 2.5 Pro SxS Pairwise Evaluation Results",
)

# Task
Import the necessary classes from `vertexai.evaluation` to access the Google Evaluation Service. Loop through all rows in the `faq_df` DataFrame. For each row, use the `get_raq_response` function to generate a bot response for the question. Collect the `question`, generated `response`, and the original `answer` (reference) into a new DataFrame.

## Import Evaluation Libraries

### Subtask:
Import the necessary classes from `vertexai.evaluation` to access the Google Evaluation Service and prepare the environment.

**Reasoning**:
Import the required libraries for Vertex AI evaluation. I will import `nest_asyncio` and apply it, and import `EvalTask` and `PointwiseMetric` from `vertexai.evaluation` as requested. `pandas` was previously imported, so I will skip re-importing it.

In [34]:
import nest_asyncio
from vertexai.evaluation import EvalTask, PointwiseMetric

# Apply nest_asyncio to enable nested event loops for async evaluation
nest_asyncio.apply()

print("Vertex AI Evaluation libraries imported and nest_asyncio applied.")

Vertex AI Evaluation libraries imported and nest_asyncio applied.

**Reasoning**:
Iterate through the `faq_df` DataFrame to generate responses using the `get_raq_response` function. Collect the questions, generated responses, and reference answers into a new DataFrame called `eval_df` for evaluation purposes.

In [35]:
questions = []
responses = []
references = []

print(f"Generating responses for {len(faq_df)} questions...")

# Iterate through the FAQ DataFrame
for index, row in faq_df.iterrows():
    question = row['question']
    reference = row['answer']

    try:
        # Generate response using the RAG function
        response = get_raq_response(question)
    except Exception as e:
        print(f"Error generating response for question '{question}': {e}")
        response = "Error generation failed"

    questions.append(question)
    responses.append(response)
    references.append(reference)

# Create a new DataFrame for evaluation
eval_df = pd.DataFrame({
    "question": questions,
    "response": responses,
    "reference": references
})

print("Evaluation dataset created.")
display(eval_df.head())

Generating responses for 50 questions...
Evaluation dataset created.

,question,response,reference
0,When was the Alaska Department of Snow establi...,The Alaska Department of Snow (ADS) was establ...,The Alaska Department of Snow (ADS) was establ...
1,What is the mission of the Alaska Department o...,"Our mission is to ensure safe, efficient trave...","Our mission is to ensure safe, efficient trave..."
2,How does ADS coordinate plowing across differe...,ADS works with local municipalities and region...,ADS works with local municipalities and region...
3,Who do I contact to report an unplowed road?,Contact your local ADS regional office. Each r...,Contact your local ADS regional office. Each r...
4,Does ADS oversee school closure decisions?,"While ADS provides data on snow conditions, fi...","While ADS provides data on snow conditions, fi..."

## Run Evaluation Task

### Subtask:
Define evaluation metrics, initialize the Vertex AI EvalTask, and execute the evaluation on the generated dataset.

**Reasoning**:
Define evaluation metrics, initialize the EvalTask with the prepared dataset, and execute the evaluation. Finally, display the summary and detailed metrics.

In [37]:
metrics = [
    "groundedness",
    "answer_relevance",
    "question_answering_quality",
]

# Initialize the EvalTask
eval_task = EvalTask(
    dataset=eval_df,
    metrics=metrics,
    experiment="alaska-snow-rag-eval"
)

print("Starting evaluation...")
# Execute the evaluation
eval_result = eval_task.evaluate()

print("Evaluation complete.")

# Print summary metrics
print("\nSummary Metrics:")
display(eval_result.summary_metrics)

# Display detailed metrics table
print("\nDetailed Metrics Table:")
display(eval_result.metrics_table.head())

Starting evaluation...

ValueError: Cannot find the `prompt` column in the evaluation dataset to fill the metric prompt template for `groundedness` metric. Please check if the column is present in the evaluation dataset, or provide a key-value pair in `metric_column_mapping` parameter of `EvalTask` to map it to a different column name. The evaluation dataset columns are ['question', 'response', 'reference'].

**Reasoning**:
The previous execution failed because `EvalTask` could not map the dataset column `question` to the expected `prompt` input for the metrics. Additionally, `groundedness` typically requires a `context` column, which is missing; I will map `prompt` to `question` and `ground_truth` to `reference`. To prevent further errors with `groundedness`, I will also map `context` to `reference` (using the reference answer as the source of truth for groundedness checking).

# Task
Define a `metric_column_mapping` dictionary that maps `prompt` to `question`, `ground_truth` to `reference`, and `context` to `reference`. Then, re-run the `eval_task.evaluate()` method passing this mapping to fix the column validation error, and display the resulting summary metrics and the head of the detailed metrics table.

## Fix Evaluation Task

### Subtask:
Define the column mapping and re-run the Vertex AI evaluation.

**Reasoning**:
I will define the `metric_column_mapping` to map the required metric inputs to the dataframe columns, re-initialize the `EvalTask` with this mapping, execute the evaluation, and display the results to fix the previous error.

In [40]:
# Define the column mapping to fix the ValueError
metric_column_mapping = {
    "prompt": "question",
    "ground_truth": "reference",
    "context": "reference"  # Using reference as context for groundedness check in this simplified setup
}

# Re-initialize the EvalTask with the mapping
eval_task = EvalTask(
    dataset=eval_df,
    metrics=metrics,
    experiment="alaska-snow-rag-eval-fixed",
    metric_column_mapping=metric_column_mapping
)

print("Starting evaluation with column mapping...")
# Execute the evaluation
eval_result = eval_task.evaluate()

print("Evaluation complete.")

# Print summary metrics
print("\nSummary Metrics:")
display(eval_result.summary_metrics)

# Display detailed metrics table
print("\nDetailed Metrics Table:")
display(eval_result.metrics_table.head())

Starting evaluation with column mapping...

  1%|          | 1/150 [00:04<10:19,  4.16s/it]

ValueError: Metric name: answer_relevance is not supported.